CREATE TABLE COMPANY (
    COMPANY_ID SERIAL PRIMARY KEY,
    COMPANY_NAME VARCHAR(50)
);

CREATE TABLE PROFILES (
    SLACK_ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(50),
    STATUS VARCHAR(140),
    COMPANY_ID INT REFERENCES COMPANY
);